name: Deploy Website

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Files
        run: ls -la

      - name: Verify Dockerfile Exists
        run: cat Dockerfile
